[package]
name = "base_client"
version = "0.1.0"
authors = ["sheosi <sertorbe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="^0.3", features = ["rt", "macros", "sync"]}
rumqttc = "^0.1"
rmp-serde = "^0.14"
rsnowboy = {git = "https://github.com/sheosi/rsnowboy"} # Hotword detector
url = "^2.1"
rodio = {version = "^0.12"} # Playback library
cpal = {version = "^0.12", optional = true} # For recording (future substitute of sphinxad)
serde = {version = "^1.0", features = ["derive"]} # Serialization framework (used by serde_yaml and serde_json)
lily_common = {path = "../common"}
anyhow = "^1.0" # For error handling overall in the app
log = "^0.4" # Common API for logging so we can change backend easily