[package]
name = "lily"
version = "0.1.0"
authors = ["sergio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "^0.4" # Load configuration files from this program and skills
serde_yaml = "^0.8"
fluent = "^0.9" # Translations and templating
serde = {version = "^1.0", features = ["derive"]} # Serialization framework (used by serde_yaml and serde_json)

rsnowboy = {git = "https://github.com/sheosi/rsnowboy"} # Hotword detector
vad = "0.1.5"
pocketsphinx = "^0.6.0" # Offline Stt
#deepspeech = {version = "^0.6", optional = true} # More correct and better (also slower) Stt 
sphinxad = "^0.1" # Recording library
cpal = {version = "^0.10", optional = true} # For recording (future substitute of sphinxad)
hound = "^3.4" # Write to wav

snips-nlu-lib = { git = "https://github.com/snipsco/snips-nlu-rs", branch = "master" } # NLU
snips-nlu-ontology = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.67.1"  } # NLU-related things
serde_json ="^1.0" # Used in nlu output and to get text from IBM's Wattson
cpython = "^0.3" # Load actions, in the future when Pyo3 works with stable we'll change this
python3-sys = "^0.3" # For PyImport_AppendInitTab

ref_thread_local = "^0.0" # For having the TTS as a global in a thread local way
ttspico = "^0.1" # Main Tts (only for some languages)
espeak-sys = {version = "^0.0", optional = true} # Auxiliar Tts (speaks any language)
libc = "^0.2" # Required to interface with espeak-sys
rodio = "^0.10" # Playback library

syslog = "^5.0" # Linux log interface
log = "^0.4" # Common API for logging so we can change backend easily

#Cloud-based
google_translate_tts = "0.1.2" # Format TTS URLs
reqwest = {version="0.10.0-alpha.2", features=["default-tls", "blocking"]} # HTTP client
base64 = "0.11.0" # For sending data to the online TTS and STT

# Localization
unic-langid = {version="^0.7", features = ["macros"]} # For parsing Unicode Language Identifiers
locale_config = "*" # Interact with the system locale, the * is suggestednby it's author
fluent-langneg = "^0.11" # Language negotiation

[features]
default = []
extra_langs_tts = ["espeak-sys"]
google_tts = []
devel_cpal_rec = ["cpal"]
devel_deepspeech = []#devel_deepspeech = ["deepspeech"]