[package]
name = "client-components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lily_common = {path = "../common"}
anyhow = "^1.0"