name: Dependabot merge branches

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
